#!/bin/sh
# MSVC only! Not using $PLATFORM from the GHA in this script.
# A valid SFML package has to have been set up already at extern/sfml/msvc.
# NOTE:	We are supposed to be in the repo's work-tree root. (And that seems
#	to be the case when being run from a GH Action.)
#!!
#!! LOTS OF THINGS HARDCODED!
#!!
#!! Package name, dl. URL, target tmp dir, `lib` subdirs, -s-s*.lib pattern,
#!! package layout etc...
#!!

# Tested with WSL bash and BusyBox-w32.
#
#! NOTE: BusyBox realpath can't do -Lms for symlinks as used in the companion
#! `sfml-setup` script, which is meant to run on native Linux with GNU `realpath`
#! to handle a missing symlink target (and/or subdir part?) etc.
#! But we're on Windows now, with SFML already set up, and BB only has to
#! resolve a relative path, symlinked or not... -- which it can do just fine.
#


TARGET=msvc
SFML_ROOT="${SZ_SFML_ROOT}"

SFML_LIBPACK_DOWNLOAD_URL_BASE="https://x1ab.github.io/download/SFML/3.0-pre/custom/"
# There's only this one now:
SFML_LIBPACK_FILE="vc17-64-staticCRT.zip"

# Set this to 'yes' for overwriting existing target libs:
OVERWRITE=${OVERWRITE:-yes}


main(){
	if [ ! -e ./tooling ]; then
		echo - ERROR: This script must be run from the project root dir.
		exit 254
	fi

	if [ "${OVERWRITE}" != "yes" ]; then
		echo "- NOTE: Not overwriting existing files."
		MV="mv -n"
		CP="cp -n"
	else
		echo "- NOTE: Existing files *WILL BE OVERWRITTEN* silently!"
		MV="mv -f"
		CP="cp -f"
	fi

	# We need the abs. path as it's gonna be ref'ed from subdirs:
	SFML_ROOT=`realpath ${SFML_ROOT}`

	# If $SFML_ROOT doesn't exist, bail out...
	if [ ! -d "$SFML_ROOT" ]; then
		echo "- ERROR: '$SFML_ROOT' doesn't exist. Aborting."
		return 1
	fi

	# If it doesn't look healthy, also bail out...
	if [ ! -d "$SFML_ROOT/include/SFML" ] || [ ! -d "$SFML_ROOT/lib" ] ; then
		echo "- ERROR: '$SFML_ROOT' doesn't look like a valid SFML package!"
		echo "  Chickening out..."
		return 2
	fi

	install
	retc=$?
	[ ! $retc -eq 0 ] && return $retc

	return 0
}

install(){
#
# The caller ought to have checked already if the target dir is OK!
#
	#
	echo Download...
	#
	_SFML_PACK_NAME="$SFML_LIBPACK_FILE"
	_SFML_DOWNLOAD_URL="$SFML_LIBPACK_DOWNLOAD_URL_BASE/$_SFML_PACK_NAME"
	# NOTE: pkg. layout: ./lib, ./include, ...

	#!! Alas, we have nothing like a `setenv` wrapper (yet) to rely on...:
	_SFML_DOWNLOAD_DIR="./tmp/${_SFML_PACK_NAME}.download.tmp"
	if [ ! -d "$_SFML_DOWNLOAD_DIR" ]; then
		echo "- NOTE: temp. download dir '$_SFML_DOWNLOAD_DIR' doesn't exist. Creating..."
		mkdir -p "$_SFML_DOWNLOAD_DIR"
	fi
	if [ ! -d "$_SFML_DOWNLOAD_DIR" ]; then
		echo "- ERROR: Couldn't create '$_SFML_DOWNLOAD_DIR'! Aborting."
		return 3
	fi

	_SFML_DOWNLOADED_PACK="$_SFML_DOWNLOAD_DIR/$_SFML_PACK_NAME"

#!!	sudo apt install wget

	#
	# If the URL is being redirected via a HTML META REFRESH: bummer!...
	# wget (or curl) doesn't support that! :-/
	# So, we need to parse the file and follow the URL manually here... :-/
	#
	# Well, currently "parsing" means assuming this exact format, and awking the URL
	# out of it using -F '=|"'...:
	#
	# <meta http-equiv="refresh" content="0; url=..." />
	#
	while [ ! -z "$_SFML_DOWNLOAD_URL" ]; do

		echo Running: "wget -q -P \"$_SFML_DOWNLOAD_DIR\" \"$_SFML_DOWNLOAD_URL\" -O \"$_SFML_DOWNLOADED_PACK\""
		               wget    -P  "$_SFML_DOWNLOAD_DIR"   "$_SFML_DOWNLOAD_URL"  -O  "$_SFML_DOWNLOADED_PACK"

		if [ ! -e "$_SFML_DOWNLOADED_PACK" ]; then
			echo "- ERROR: Failed to download package '$_SFML_DOWNLOAD_URL'."
			return 4
		fi

		unset url
		grep -iq '<meta http-equiv="refresh"' $_SFML_DOWNLOADED_PACK && \
			url=`awk -F '=|"' -- '{print $7}' "$_SFML_DOWNLOADED_PACK"`
		echo $url
		_SFML_DOWNLOAD_URL=$url
	done

	#
	echo Unpack...
	#
	# Goto the dl. dir for some ad-hoc poor man's sandboxing... ;)
	cd "$_SFML_DOWNLOAD_DIR"
	if [ ! $? -eq 0 ]; then
	    echo "- ERROR: Failed to enter '"$_SFML_DOWNLOAD_DIR"' - not a dir?!"
	    return 5
	fi

	unzip `basename "$_SFML_DOWNLOADED_PACK"`
		# I just couldn't find out a priori whether the GHA runner has unzip or not...
		# I've read the relevant GitHub pages, googled, asked ChatGPT, read SO posts,
		# but: all inconclusive... Sigh. We'll see from the errors then. :-/
	## Alternatively, only unpack the libs (but the prebuilt is rarely the same version!):
	#unzip `basename "$_SFML_DOWNLOADED_PACK"` *.lib

	if [ ! $? -eq 0 ]; then
		echo "- ERROR: Failed to unpack '$_SFML_DOWNLOADED_PACK'."
		return 6
	fi

	#
	echo "Move the addon libs & includes to $SFML_ROOT..."
	#
	if [ $? -eq 0 ] && [ -e "$SFML_ROOT/lib" ] && [ -e "$SFML_ROOT/include" ]; then
		${MV} lib/*-s-s*.lib $SFML_ROOT/lib/
		if [ ! $? -eq 0 ]; then
			echo "- ERROR: Failed to move content to '$SFML_ROOT/lib/'! Aborting."
			return 7
		fi
#!!WTF, all I got is tantrum from mv:
#!!??		${MV} -f include/* $SFML_ROOT/include/
#!!??		${MV} -f -t $SFML_ROOT/include/ include/*
		${CP} -r include/* $SFML_ROOT/include/
		if [ ! $? -eq 0 ]; then
			echo "- ERROR: Failed to move content to '$SFML_ROOT/include/'! Aborting."
			return 7
		fi
	else
		echo "- ERROR: Unexpected SFML dir layout ($SFML_ROOT)"
		echo "  No 'lib' or 'include' subdirs!"
		return 8
	fi

	return 0
}

#-----------------------------------------------------------------------------
dirsave=`pwd`
main
retc=$?
cd $dirsave
if [ $? -ne 0 ]; then
	echo "- ERROR: SFML addon-libs setup failed!"
	exit 1
fi
exit 0
